version: '3'
services:
  redis:
    image: redis
    container_name: redis
    networks:
      - appnet

  app:
    image: omer019/my-python-app:latest
    container_name: app
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - appnet

networks:
  appnet: